"""Remove unique from invoice_number

Revision ID: a25747705bae
Revises: 20260105_000004
Create Date: 2026-01-08 19:18:37.526018

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25747705bae'
down_revision = '20260105_000004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    # ### end Alembic commands ###


